# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/albaud/Documents/Programation/scop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/albaud/Documents/Programation/scop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/albaud/Documents/Programation/scop/CMakeFiles /Users/albaud/Documents/Programation/scop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/albaud/Documents/Programation/scop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scop

# Build rule for target.
scop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scop
.PHONY : scop

# fast build rule for target.
scop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/build
.PHONY : scop/fast

src/image/PPM.o: src/image/PPM.cpp.o
.PHONY : src/image/PPM.o

# target to build an object file
src/image/PPM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/image/PPM.cpp.o
.PHONY : src/image/PPM.cpp.o

src/image/PPM.i: src/image/PPM.cpp.i
.PHONY : src/image/PPM.i

# target to preprocess a source file
src/image/PPM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/image/PPM.cpp.i
.PHONY : src/image/PPM.cpp.i

src/image/PPM.s: src/image/PPM.cpp.s
.PHONY : src/image/PPM.s

# target to generate assembly for a file
src/image/PPM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/image/PPM.cpp.s
.PHONY : src/image/PPM.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/vulkan/Buffer/Buffer.o: src/vulkan/Buffer/Buffer.cpp.o
.PHONY : src/vulkan/Buffer/Buffer.o

# target to build an object file
src/vulkan/Buffer/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Buffer/Buffer.cpp.o
.PHONY : src/vulkan/Buffer/Buffer.cpp.o

src/vulkan/Buffer/Buffer.i: src/vulkan/Buffer/Buffer.cpp.i
.PHONY : src/vulkan/Buffer/Buffer.i

# target to preprocess a source file
src/vulkan/Buffer/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Buffer/Buffer.cpp.i
.PHONY : src/vulkan/Buffer/Buffer.cpp.i

src/vulkan/Buffer/Buffer.s: src/vulkan/Buffer/Buffer.cpp.s
.PHONY : src/vulkan/Buffer/Buffer.s

# target to generate assembly for a file
src/vulkan/Buffer/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Buffer/Buffer.cpp.s
.PHONY : src/vulkan/Buffer/Buffer.cpp.s

src/vulkan/CommandBuffer/SingleUseCommandBuffer.o: src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.o
.PHONY : src/vulkan/CommandBuffer/SingleUseCommandBuffer.o

# target to build an object file
src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.o
.PHONY : src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.o

src/vulkan/CommandBuffer/SingleUseCommandBuffer.i: src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.i
.PHONY : src/vulkan/CommandBuffer/SingleUseCommandBuffer.i

# target to preprocess a source file
src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.i
.PHONY : src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.i

src/vulkan/CommandBuffer/SingleUseCommandBuffer.s: src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.s
.PHONY : src/vulkan/CommandBuffer/SingleUseCommandBuffer.s

# target to generate assembly for a file
src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.s
.PHONY : src/vulkan/CommandBuffer/SingleUseCommandBuffer.cpp.s

src/vulkan/Device/Decive.o: src/vulkan/Device/Decive.cpp.o
.PHONY : src/vulkan/Device/Decive.o

# target to build an object file
src/vulkan/Device/Decive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Device/Decive.cpp.o
.PHONY : src/vulkan/Device/Decive.cpp.o

src/vulkan/Device/Decive.i: src/vulkan/Device/Decive.cpp.i
.PHONY : src/vulkan/Device/Decive.i

# target to preprocess a source file
src/vulkan/Device/Decive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Device/Decive.cpp.i
.PHONY : src/vulkan/Device/Decive.cpp.i

src/vulkan/Device/Decive.s: src/vulkan/Device/Decive.cpp.s
.PHONY : src/vulkan/Device/Decive.s

# target to generate assembly for a file
src/vulkan/Device/Decive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Device/Decive.cpp.s
.PHONY : src/vulkan/Device/Decive.cpp.s

src/vulkan/Instance/Instance.o: src/vulkan/Instance/Instance.cpp.o
.PHONY : src/vulkan/Instance/Instance.o

# target to build an object file
src/vulkan/Instance/Instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Instance/Instance.cpp.o
.PHONY : src/vulkan/Instance/Instance.cpp.o

src/vulkan/Instance/Instance.i: src/vulkan/Instance/Instance.cpp.i
.PHONY : src/vulkan/Instance/Instance.i

# target to preprocess a source file
src/vulkan/Instance/Instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Instance/Instance.cpp.i
.PHONY : src/vulkan/Instance/Instance.cpp.i

src/vulkan/Instance/Instance.s: src/vulkan/Instance/Instance.cpp.s
.PHONY : src/vulkan/Instance/Instance.s

# target to generate assembly for a file
src/vulkan/Instance/Instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Instance/Instance.cpp.s
.PHONY : src/vulkan/Instance/Instance.cpp.s

src/vulkan/PhysicalDevice/PhysicalDevice.o: src/vulkan/PhysicalDevice/PhysicalDevice.cpp.o
.PHONY : src/vulkan/PhysicalDevice/PhysicalDevice.o

# target to build an object file
src/vulkan/PhysicalDevice/PhysicalDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/PhysicalDevice/PhysicalDevice.cpp.o
.PHONY : src/vulkan/PhysicalDevice/PhysicalDevice.cpp.o

src/vulkan/PhysicalDevice/PhysicalDevice.i: src/vulkan/PhysicalDevice/PhysicalDevice.cpp.i
.PHONY : src/vulkan/PhysicalDevice/PhysicalDevice.i

# target to preprocess a source file
src/vulkan/PhysicalDevice/PhysicalDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/PhysicalDevice/PhysicalDevice.cpp.i
.PHONY : src/vulkan/PhysicalDevice/PhysicalDevice.cpp.i

src/vulkan/PhysicalDevice/PhysicalDevice.s: src/vulkan/PhysicalDevice/PhysicalDevice.cpp.s
.PHONY : src/vulkan/PhysicalDevice/PhysicalDevice.s

# target to generate assembly for a file
src/vulkan/PhysicalDevice/PhysicalDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/PhysicalDevice/PhysicalDevice.cpp.s
.PHONY : src/vulkan/PhysicalDevice/PhysicalDevice.cpp.s

src/vulkan/Pipeline/Pipeline.o: src/vulkan/Pipeline/Pipeline.cpp.o
.PHONY : src/vulkan/Pipeline/Pipeline.o

# target to build an object file
src/vulkan/Pipeline/Pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Pipeline/Pipeline.cpp.o
.PHONY : src/vulkan/Pipeline/Pipeline.cpp.o

src/vulkan/Pipeline/Pipeline.i: src/vulkan/Pipeline/Pipeline.cpp.i
.PHONY : src/vulkan/Pipeline/Pipeline.i

# target to preprocess a source file
src/vulkan/Pipeline/Pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Pipeline/Pipeline.cpp.i
.PHONY : src/vulkan/Pipeline/Pipeline.cpp.i

src/vulkan/Pipeline/Pipeline.s: src/vulkan/Pipeline/Pipeline.cpp.s
.PHONY : src/vulkan/Pipeline/Pipeline.s

# target to generate assembly for a file
src/vulkan/Pipeline/Pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Pipeline/Pipeline.cpp.s
.PHONY : src/vulkan/Pipeline/Pipeline.cpp.s

src/vulkan/QueueFamilyIndices/QueueFamilyIndices.o: src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.o
.PHONY : src/vulkan/QueueFamilyIndices/QueueFamilyIndices.o

# target to build an object file
src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.o
.PHONY : src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.o

src/vulkan/QueueFamilyIndices/QueueFamilyIndices.i: src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.i
.PHONY : src/vulkan/QueueFamilyIndices/QueueFamilyIndices.i

# target to preprocess a source file
src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.i
.PHONY : src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.i

src/vulkan/QueueFamilyIndices/QueueFamilyIndices.s: src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.s
.PHONY : src/vulkan/QueueFamilyIndices/QueueFamilyIndices.s

# target to generate assembly for a file
src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.s
.PHONY : src/vulkan/QueueFamilyIndices/QueueFamilyIndices.cpp.s

src/vulkan/RenderPass.o: src/vulkan/RenderPass.cpp.o
.PHONY : src/vulkan/RenderPass.o

# target to build an object file
src/vulkan/RenderPass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/RenderPass.cpp.o
.PHONY : src/vulkan/RenderPass.cpp.o

src/vulkan/RenderPass.i: src/vulkan/RenderPass.cpp.i
.PHONY : src/vulkan/RenderPass.i

# target to preprocess a source file
src/vulkan/RenderPass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/RenderPass.cpp.i
.PHONY : src/vulkan/RenderPass.cpp.i

src/vulkan/RenderPass.s: src/vulkan/RenderPass.cpp.s
.PHONY : src/vulkan/RenderPass.s

# target to generate assembly for a file
src/vulkan/RenderPass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/RenderPass.cpp.s
.PHONY : src/vulkan/RenderPass.cpp.s

src/vulkan/Surface/Surface.o: src/vulkan/Surface/Surface.cpp.o
.PHONY : src/vulkan/Surface/Surface.o

# target to build an object file
src/vulkan/Surface/Surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Surface/Surface.cpp.o
.PHONY : src/vulkan/Surface/Surface.cpp.o

src/vulkan/Surface/Surface.i: src/vulkan/Surface/Surface.cpp.i
.PHONY : src/vulkan/Surface/Surface.i

# target to preprocess a source file
src/vulkan/Surface/Surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Surface/Surface.cpp.i
.PHONY : src/vulkan/Surface/Surface.cpp.i

src/vulkan/Surface/Surface.s: src/vulkan/Surface/Surface.cpp.s
.PHONY : src/vulkan/Surface/Surface.s

# target to generate assembly for a file
src/vulkan/Surface/Surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Surface/Surface.cpp.s
.PHONY : src/vulkan/Surface/Surface.cpp.s

src/vulkan/SwapChain/SwapChain.o: src/vulkan/SwapChain/SwapChain.cpp.o
.PHONY : src/vulkan/SwapChain/SwapChain.o

# target to build an object file
src/vulkan/SwapChain/SwapChain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/SwapChain/SwapChain.cpp.o
.PHONY : src/vulkan/SwapChain/SwapChain.cpp.o

src/vulkan/SwapChain/SwapChain.i: src/vulkan/SwapChain/SwapChain.cpp.i
.PHONY : src/vulkan/SwapChain/SwapChain.i

# target to preprocess a source file
src/vulkan/SwapChain/SwapChain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/SwapChain/SwapChain.cpp.i
.PHONY : src/vulkan/SwapChain/SwapChain.cpp.i

src/vulkan/SwapChain/SwapChain.s: src/vulkan/SwapChain/SwapChain.cpp.s
.PHONY : src/vulkan/SwapChain/SwapChain.s

# target to generate assembly for a file
src/vulkan/SwapChain/SwapChain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/SwapChain/SwapChain.cpp.s
.PHONY : src/vulkan/SwapChain/SwapChain.cpp.s

src/vulkan/SwapChain/SwapchainChooser.o: src/vulkan/SwapChain/SwapchainChooser.cpp.o
.PHONY : src/vulkan/SwapChain/SwapchainChooser.o

# target to build an object file
src/vulkan/SwapChain/SwapchainChooser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/SwapChain/SwapchainChooser.cpp.o
.PHONY : src/vulkan/SwapChain/SwapchainChooser.cpp.o

src/vulkan/SwapChain/SwapchainChooser.i: src/vulkan/SwapChain/SwapchainChooser.cpp.i
.PHONY : src/vulkan/SwapChain/SwapchainChooser.i

# target to preprocess a source file
src/vulkan/SwapChain/SwapchainChooser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/SwapChain/SwapchainChooser.cpp.i
.PHONY : src/vulkan/SwapChain/SwapchainChooser.cpp.i

src/vulkan/SwapChain/SwapchainChooser.s: src/vulkan/SwapChain/SwapchainChooser.cpp.s
.PHONY : src/vulkan/SwapChain/SwapchainChooser.s

# target to generate assembly for a file
src/vulkan/SwapChain/SwapchainChooser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/SwapChain/SwapchainChooser.cpp.s
.PHONY : src/vulkan/SwapChain/SwapchainChooser.cpp.s

src/vulkan/VImage/VImage.o: src/vulkan/VImage/VImage.cpp.o
.PHONY : src/vulkan/VImage/VImage.o

# target to build an object file
src/vulkan/VImage/VImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/VImage/VImage.cpp.o
.PHONY : src/vulkan/VImage/VImage.cpp.o

src/vulkan/VImage/VImage.i: src/vulkan/VImage/VImage.cpp.i
.PHONY : src/vulkan/VImage/VImage.i

# target to preprocess a source file
src/vulkan/VImage/VImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/VImage/VImage.cpp.i
.PHONY : src/vulkan/VImage/VImage.cpp.i

src/vulkan/VImage/VImage.s: src/vulkan/VImage/VImage.cpp.s
.PHONY : src/vulkan/VImage/VImage.s

# target to generate assembly for a file
src/vulkan/VImage/VImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/VImage/VImage.cpp.s
.PHONY : src/vulkan/VImage/VImage.cpp.s

src/vulkan/ValidationLayers/ValidationLayers.o: src/vulkan/ValidationLayers/ValidationLayers.cpp.o
.PHONY : src/vulkan/ValidationLayers/ValidationLayers.o

# target to build an object file
src/vulkan/ValidationLayers/ValidationLayers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/ValidationLayers/ValidationLayers.cpp.o
.PHONY : src/vulkan/ValidationLayers/ValidationLayers.cpp.o

src/vulkan/ValidationLayers/ValidationLayers.i: src/vulkan/ValidationLayers/ValidationLayers.cpp.i
.PHONY : src/vulkan/ValidationLayers/ValidationLayers.i

# target to preprocess a source file
src/vulkan/ValidationLayers/ValidationLayers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/ValidationLayers/ValidationLayers.cpp.i
.PHONY : src/vulkan/ValidationLayers/ValidationLayers.cpp.i

src/vulkan/ValidationLayers/ValidationLayers.s: src/vulkan/ValidationLayers/ValidationLayers.cpp.s
.PHONY : src/vulkan/ValidationLayers/ValidationLayers.s

# target to generate assembly for a file
src/vulkan/ValidationLayers/ValidationLayers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/ValidationLayers/ValidationLayers.cpp.s
.PHONY : src/vulkan/ValidationLayers/ValidationLayers.cpp.s

src/vulkan/Window/Window.o: src/vulkan/Window/Window.cpp.o
.PHONY : src/vulkan/Window/Window.o

# target to build an object file
src/vulkan/Window/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Window/Window.cpp.o
.PHONY : src/vulkan/Window/Window.cpp.o

src/vulkan/Window/Window.i: src/vulkan/Window/Window.cpp.i
.PHONY : src/vulkan/Window/Window.i

# target to preprocess a source file
src/vulkan/Window/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Window/Window.cpp.i
.PHONY : src/vulkan/Window/Window.cpp.i

src/vulkan/Window/Window.s: src/vulkan/Window/Window.cpp.s
.PHONY : src/vulkan/Window/Window.s

# target to generate assembly for a file
src/vulkan/Window/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scop.dir/build.make CMakeFiles/scop.dir/src/vulkan/Window/Window.cpp.s
.PHONY : src/vulkan/Window/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... scop"
	@echo "... src/image/PPM.o"
	@echo "... src/image/PPM.i"
	@echo "... src/image/PPM.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/vulkan/Buffer/Buffer.o"
	@echo "... src/vulkan/Buffer/Buffer.i"
	@echo "... src/vulkan/Buffer/Buffer.s"
	@echo "... src/vulkan/CommandBuffer/SingleUseCommandBuffer.o"
	@echo "... src/vulkan/CommandBuffer/SingleUseCommandBuffer.i"
	@echo "... src/vulkan/CommandBuffer/SingleUseCommandBuffer.s"
	@echo "... src/vulkan/Device/Decive.o"
	@echo "... src/vulkan/Device/Decive.i"
	@echo "... src/vulkan/Device/Decive.s"
	@echo "... src/vulkan/Instance/Instance.o"
	@echo "... src/vulkan/Instance/Instance.i"
	@echo "... src/vulkan/Instance/Instance.s"
	@echo "... src/vulkan/PhysicalDevice/PhysicalDevice.o"
	@echo "... src/vulkan/PhysicalDevice/PhysicalDevice.i"
	@echo "... src/vulkan/PhysicalDevice/PhysicalDevice.s"
	@echo "... src/vulkan/Pipeline/Pipeline.o"
	@echo "... src/vulkan/Pipeline/Pipeline.i"
	@echo "... src/vulkan/Pipeline/Pipeline.s"
	@echo "... src/vulkan/QueueFamilyIndices/QueueFamilyIndices.o"
	@echo "... src/vulkan/QueueFamilyIndices/QueueFamilyIndices.i"
	@echo "... src/vulkan/QueueFamilyIndices/QueueFamilyIndices.s"
	@echo "... src/vulkan/RenderPass.o"
	@echo "... src/vulkan/RenderPass.i"
	@echo "... src/vulkan/RenderPass.s"
	@echo "... src/vulkan/Surface/Surface.o"
	@echo "... src/vulkan/Surface/Surface.i"
	@echo "... src/vulkan/Surface/Surface.s"
	@echo "... src/vulkan/SwapChain/SwapChain.o"
	@echo "... src/vulkan/SwapChain/SwapChain.i"
	@echo "... src/vulkan/SwapChain/SwapChain.s"
	@echo "... src/vulkan/SwapChain/SwapchainChooser.o"
	@echo "... src/vulkan/SwapChain/SwapchainChooser.i"
	@echo "... src/vulkan/SwapChain/SwapchainChooser.s"
	@echo "... src/vulkan/VImage/VImage.o"
	@echo "... src/vulkan/VImage/VImage.i"
	@echo "... src/vulkan/VImage/VImage.s"
	@echo "... src/vulkan/ValidationLayers/ValidationLayers.o"
	@echo "... src/vulkan/ValidationLayers/ValidationLayers.i"
	@echo "... src/vulkan/ValidationLayers/ValidationLayers.s"
	@echo "... src/vulkan/Window/Window.o"
	@echo "... src/vulkan/Window/Window.i"
	@echo "... src/vulkan/Window/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

